### PR TITLE
Allow for multiple applications in the sudo rule

### PR DESCRIPTION
**Pull request by mattj-io**

### CODE REVIEW

**Comment by seanhandley** [comment]
Is this _ever_ getting merged.... ?

**Comment by mattj-io** [comment]
Good point

**Comment by mattj-io** [comment]
Can I get some thumbs pls ?

**Comment by seanhandley** [comment]
:+1:

**Comment by yankcrime** [comment]
:+1:

**Comment by bilco105** [comment]
:+1: :wink:

**Comment by seanhandley** [comment]
Mario

**Pull request merged**
